### ISSUE TITLE
Missing required prop: "areas"

### ISSUE THREAD

**Issue by moisespio** [ederchrono/vue-css-grid#5]
Why area is a required prop? In order to use CSS grid, we actually don't need to specify the area property. So my guess is that prop is supposed to be optional, right?

**Comment by ederchrono** [comment]
Areas are right now required because there's no implementation of tracks, flow, order and other parts of the grid specification, the components were made to make a layout just in that way. 
I'm currently working on doing a v1 release that works either with areas or columns-rows start-end properties, so that it can be more flexible. 
If you have ay feedback or suggestions on what would you like to see next, it would be awesome!

**Comment by moisespio** [comment]
Sounds good! That's all I have so far, but I'll let you know if anything else comes up. Thanks for the component though, pretty handy :)

Cheers,

**Comment by ederchrono** [comment]
v1.0.0 update
Areas are not required anymore!
